baseURL = 'https://caisong.github.io'
languageCode = 'en-us'
title = "Caisong's Blog"
theme = "dream"

[params]
  author = "Cai Song"
  description = "A blog about all things technical."

  [[params.social]]
    icon = "github"
    name = "GitHub"
    url = "https://github.com/caisong"

