baseURL = 'https://caisong.github.io'
languageCode = 'en-us'
title = "Caisong's Blog"
theme = "dream"

[params]
author = "Cai Song"
headerTitle = "A blog about all things technical."
lightTheme = "emerald"
darkTheme = "forest"
siteStartYear = 2016
rss = true

email = "ujscs@live.cn"
# #Syntax highlighting
# customSyntaxHighlighting = true

# options
 stickyNav = true
 reorderNavItems = ["search", "rss", "posts", "categories", "tags"]
 collapseNavItems = ["posts", "categories", "tags"]
 noDefaultSummaryCover = true
 showTableOfContents = true
 showSummaryCoverInPost = true
 imageZoomableInPost = true
 showPrevNextPost = true

